version: "3"
services:
  influx:
    image: influxdb
    ports:
      - 8086:8086
    environment:
      INFLUXDB_DB: database
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: password
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_HTTP_FLUX_ENABLED: "true"
      INFLUXDB_HTTP_MAX_BODY_SIZE: 0
    volumes:
      - ./influx:/var/lib/influxdb
    networks:
      admin:

  chronograf:
    image: chronograf:latest
    ports: 
        - '8887:8888'
    depends_on: 
        - influx
    environment: 
      - INFLUXDB_URL=http://influx:8086
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=password
    networks:
        admin:
        
  grafana:
    image: grafana/grafana:latest
    restart: always
    volumes:
      - ./grafana/:/etc/grafana/
    expose:
      - 3000
    networks:
      - admin:
      
networks:
  admin:
